# Generated by Django 2.1.1 on 2018-09-21 02:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happiness_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappinessLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=3)),
                ('date', models.DateField(default=datetime.date(2018, 9, 20))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happiness_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='happiness_app.Team'),
        ),
    ]
