# Generated by Django 2.1.1 on 2018-09-23 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness_app', '0002_auto_20180920_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happinesslevel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 9, 23)),
        ),
        migrations.AlterField(
            model_name='happinesslevel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
