# Generated by Django 2.1.1 on 2018-09-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness_app', '0004_auto_20180923_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happinesslevel',
            name='level',
            field=models.IntegerField(choices=[(1, 'Unhappy'), (2, 'Not Happy'), (3, 'Neutral'), (4, 'Happy'), (5, 'Very Happy')]),
        ),
    ]
