# Generated by Django 2.1.1 on 2018-09-25 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness_app', '0005_auto_20180923_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happinesslevel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 9, 25)),
        ),
    ]
